title = "angellst58 blog"
baseURL = 'https://angellst58.me/'

languageCode = 'es-es'
defaultContentLanguage = "es-es"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
theme = "hugo-blog-awesome"

[services]
  [services.googleAnalytics]
    id = '' # G-MEASUREMENT_ID

  [services.disqus]
    shortname = ''

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[Languages.es-es]
  languageName = "Español"
  languageCode = "es-es"
  contentDir = "content/posts"  # Directorio de contenido ajustado
  weight = 1

  [Languages.es-es.menu]
    [[Languages.es-es.menu.main]]
      pageRef="/"
      name = 'Inicio'
      url = '/'
      weight = 10
    [[Languages.es-es.menu.main]]
      pageRef="posts"
      name = 'Publicaciones'
      url = '/posts/'
      weight = 20
    [[Languages.es-es.menu.main]]
      pageRef = "contacto"
      name = 'Contacto'
      url = '/contacto/'
      weight = 30

[Languages.es-es.params]
  sitename = "angellst58"
  defaultColor = "dark"
  description = "Tema minimalista de Hugo con soporte para modo claro y oscuro"
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = "2 January 2006"
  rssFeedDescription = "summary"

  [Languages.es-es.params.author]
    avatar = "avatar.jpg"
    intro = "angellst58"
    name = "Angel L."
    description = "Cristiano, GNU/Linux y FOSS entusiasta, desarrollador frontend."

  [Languages.es-es.params.webmanifest]
    name = "sitename"
    short_name = "sitename"
    start_url = "/"
    theme_color = "#434648"
    background_color = "#fff"
    display = "standalone"

[params.browserconfig]
  TileColor = "#2d89ef"

[[params.socialIcons]]
name = "github"
url = "https://github.com/angellst58"
